-- drop objects
drop table d03_tipo_prodotto cascade constraints;
drop table d03_prodotto cascade constraints;
drop table d03_cliente cascade constraints;
drop table d03_fornitore cascade constraints;
drop table d03_acquisto cascade constraints;
drop table d03_vendita cascade constraints;

-- create tables
create table d03_tipo_prodotto (
    id                             number generated by default on null as identity 
                                   constraint d03_tipo_prodotto_id_pk primary key,
    tipo_prodotto                  varchar2(50 char)
                                   constraint d03_tipo_prodot_tipo_prodo_unq unique not null,
    gruppo                         varchar2(50 char) not null
)
;

create table d03_prodotto (
    id                             number generated by default on null as identity 
                                   constraint d03_prodotto_id_pk primary key,
    tipo_prodotto_id               number
                                   constraint d03_prodotto_tipo_prodotto_fk
                                   references d03_tipo_prodotto not null,
    prodotto                       varchar2(50 char) not null,
    prezzo_acquisto                number not null,
    prezzo_vendita                 number not null
)
;

-- table index
create index d03_prodotto_i1 on d03_prodotto (tipo_prodotto_id);

create table d03_cliente (
    id                             number generated by default on null as identity 
                                   constraint d03_cliente_id_pk primary key,
    cliente                        varchar2(50 char)
                                   constraint d03_cliente_cliente_unq unique not null,
    zona                           varchar2(10 char) not null
)
;

create table d03_fornitore (
    id                             number generated by default on null as identity 
                                   constraint d03_fornitore_id_pk primary key,
    fornitore                      varchar2(50 char)
                                   constraint d03_fornitore_fornitore_unq unique not null,
    zona                           varchar2(50 char) not null
)
;

create table d03_acquisto (
    id                             number generated by default on null as identity 
                                   constraint d03_acquisto_id_pk primary key,
    fornitore_id                   number
                                   constraint d03_acquisto_fornitore_id_fk
                                   references d03_fornitore not null,
    prodotto_id                    number
                                   constraint d03_acquisto_prodotto_id_fk
                                   references d03_prodotto not null,
    data                           date not null,
    quantita                       number not null
)
;

-- table index
create index d03_acquisto_i1 on d03_acquisto (fornitore_id);
create index d03_acquisto_i132 on d03_acquisto (prodotto_id);

create table d03_vendita (
    id                             number generated by default on null as identity 
                                   constraint d03_vendita_id_pk primary key,
    cliente_id                     number
                                   constraint d03_vendita_cliente_id_fk
                                   references d03_cliente not null,
    prodotto_id                    number
                                   constraint d03_vendita_prodotto_id_fk
                                   references d03_prodotto not null,
    data                           date not null,
    quantita                       number not null
)
;

-- table index
create index d03_vendita_i1 on d03_vendita (cliente_id);
create index d03_vendita_i182 on d03_vendita (prodotto_id);

-- load data
 
-- Generated by Quick SQL Tuesday March 28, 2023  09:11:49
 
/*
tipo prodotto
  tipo prodotto vc50 /nn /unique
  gruppo vc50 /nn
prodotto
  prodotto vc50 /nn
  prezzo acquisto num /nn
  prezzo vendita num /nn
  tipo_prodotto_id /nn
cliente
  cliente vc50 /nn /unique
  zona vc10 /nn
fornitore
  fornitore vc50 /nn /unique
  zona vc50 /nn
acquisto
  data d /nn
  fornitore_id /nn
  prodotto_id /nn
  quantita num /nn
vendita
  data d /nn
  cliente_id  /nn
  prodotto_id /nn
  quantita num /nn
# settings = { prefix: "D03", onDelete: "RESTRICT", semantics: "CHAR", drop: true, language: "EN", APEX: true }
*/
