
	select sum(nvl(:PREZZO_VENDITA,0)-nvl(:PREZZO_ACQUISTO,0))
	  from D08_Prodotto
	 where (:P3_PRODOTTO IS NULL OR PRODOTTO_ID in (select column_value from apex_string.split( :P3_PRODOTTO,':')))

ALTER TABLE  "D08_VENDITA" DROP CONSTRAINT "D08_VENDITA_PRODOTTO_ID_FK";
ALTER TABLE  "D08_VENDITA" ADD CONSTRAINT "D08_VENDITA_PRODOTTO_ID_FK" FOREIGN KEY ("PRODOTTO_ID") REFERENCES  "D08_PRODOTTO" ("ID") ON DELETE CASCADE;

ALTER TABLE  "D08_PRODOTTO" DROP CONSTRAINT "D08_PRODOTTO_TIPO_PRODOTTO_FK";
ALTER TABLE  "D08_PRODOTTO" ADD CONSTRAINT "D08_PRODOTTO_TIPO_PRODOTTO_FK" FOREIGN KEY ("TIPO_PRODOTTO_ID") REFERENCES  "D08_TIPO_PRODOTTO" ("ID") ON DELETE CASCADE;

ALTER TABLE  "D08_ACQUISTO" DROP CONSTRAINT "D08_ACQUISTO_PRODOTTO_ID_FK";
ALTER TABLE  "D08_ACQUISTO" ADD CONSTRAINT "D08_ACQUISTO_PRODOTTO_ID_FK" FOREIGN KEY ("PRODOTTO_ID") REFERENCES  "D08_PRODOTTO" ("ID") ON DELETE CASCADE;