create table d17_vendita (
    id  number generated by default on null as identity 
        constraint d17_vendita_id_pk primary key,
    data date, 
	prodotto varchar2(50), 
	cliente varchar2(50), 
	zona_cliente varchar2(50), 
	quantita number, 
	importo number
)
;

insert into d17_vendita (data,prodotto,cliente,zona_cliente,quantita,importo) 
select data,prodotto,cliente,zona_cliente,quantita,importo from d16_vendita;
