-- drop objects
drop table d18_automezzo cascade constraints;
drop table d18_assicurazione cascade constraints;
drop table d18_proprietario cascade constraints;

-- create tables
create table d18_automezzo (
    id                             number generated by default on null as identity 
                                   constraint d18_automezzo_id_pk primary key,
    targa                          varchar2(10 char)
                                   constraint d18_automezzo_targa_unq unique not null,
    automezzo                      varchar2(50 char) not null
)
;

create table d18_assicurazione (
    id                             number generated by default on null as identity 
                                   constraint d18_assicurazione_id_pk primary key,
    automezzo_id                   number
                                   constraint d18_assicurazio_automezzo_i_fk
                                   references d18_automezzo on delete cascade not null,
    assicurazione                  varchar2(20 char)
                                   constraint d18_assicurazio_assicurazi_unq unique not null,
    data_scadenza                  date not null
)
;

-- table index
create index d18_assicurazione_i1 on d18_assicurazione (automezzo_id);

create table d18_proprietario (
    id                             number generated by default on null as identity 
                                   constraint d18_proprietario_id_pk primary key,
    automezzo_id                   number
                                   constraint d18_proprietari_automezzo_i_fk
                                   references d18_automezzo on delete cascade not null,
    proprietario                   varchar2(50 char) not null,
    data_inizio                    date not null,
    data_fine                      date
)
;

-- table index
create index d18_proprietario_i1 on d18_proprietario (automezzo_id);

create unique index d18_assicurazione_uq1 on d18_assicurazione (automezzo_id,data_scadenza);
create unique index d18_proprietario_uq1  on d18_proprietario  (automezzo_id,data_fine);

insert into d18_automezzo (
    id,
    targa,
    automezzo
) values (
    1,
    'AA123BB',
    'AUDI'
);

insert into d18_automezzo (
    id,
    targa,
    automezzo
) values (
    2,
    'BB234CC',
    'FIAT'
);

insert into d18_automezzo (
    id,
    targa,
    automezzo
) values (
    3,
    'CC345DD',
    'BMW'
);

commit;

alter table d18_automezzo
modify id generated always as identity restart start with 4;
 
-- Generated by Quick SQL Martedì Maggio 23, 2023  06:04:01
 
/*
automezzo
  targa vc10 /nn /unique
  automezzo vc50 /nn

assicurazione
  assicurazione vc20 /nn /unique
  automezzo_id /nn
  data_scadenza d /nn

proprietario
  proprietario vc50 /nn
  automezzo_id /nn
  data_inizio d /nn
  data_fine d

# settings = { prefix: "d18", semantics: "CHAR", drop: true, language: "EN", APEX: true }
*/
