create table  d18_vendita 
   (
    id number generated by default on null as identity, 
	data date, 
	prodotto varchar2(50), 
	cliente varchar2(50), 
	zona_cliente varchar2(50), 
	quantita number, 
	importo number, 
	 constraint d18_vendita_id_pk primary key (id)
   )
/
