-- create tables
create table d201_documento (
    id                             number generated by default on null as identity 
                                   constraint d201_documento_id_pk primary key,
    codice                         varchar2(20 char)
                                   constraint d201_documento_codice_unq unique not null,
    descrizione                    varchar2(50 char) not null,
    data                           date not null,
    richiedente                    varchar2(50 char) not null,
    stato                          varchar2(20 char) default on null '10-RESP' not null
)
;

-- load data
 
-- Generated by Quick SQL Sabato Maggio 27, 2023  11:53:22
 
/*
documento
  codice vc20 /nn /unique
  descrizione vc50 /nn
  data d /nn
  richiedente vc50 /nn
  stato vc20 /nn /default 10-RESP

# settings = { prefix: "D201", semantics: "CHAR", language: "EN", APEX: true }
*/
