-- create tables
create table d20_stato (
    id                             number generated by default on null as identity 
                                   constraint d20_stato_id_pk primary key,
    stato                          varchar2(20 char)
                                   constraint d20_stato_stato_unq unique not null
)
;

create table d20_documento (
    id                             number generated by default on null as identity 
                                   constraint d20_documento_id_pk primary key,
    stato_id                       number
                                   constraint d20_documento_stato_id_fk
                                   references d20_stato on delete cascade not null,
    codice                         varchar2(20 char)
                                   constraint d20_documento_codice_unq unique not null,
    descrizione                    varchar2(50 char) not null,
    data                           date not null,
    richiedente                    varchar2(50 char) not null
)
;

-- table index
create index d20_documento_i1 on d20_documento (stato_id);

create table d20_documento_dettaglio (
    id                             number generated by default on null as identity 
                                   constraint d20_documento_dett_id_pk primary key,
    documento_id                   number
                                   constraint d20_documento_d_documento_i_fk
                                   references d20_documento on delete cascade not null,
    data                           date not null,
    utente                         varchar2(50 char) not null,
    azione                         varchar2(20 char) not null,
    stato_da_id                    number
                                   constraint d20_documento_d_stato_da_id_fk
                                   references d20_stato on delete cascade,
    stato_a_id                     number
                                   constraint d20_documento_d_stato_a_id_fk
                                   references d20_stato on delete cascade
)
;

-- table index
create index d20_documento_dett_i1 on d20_documento_dettaglio (documento_id);
create index d20_documento_dett_i112 on d20_documento_dettaglio (stato_a_id);
create index d20_documento_dett_i123 on d20_documento_dettaglio (stato_da_id);

-- load data
 
-- Generated by Quick SQL Saturday May 27, 2023  06:36:56
 
/*
stato
  stato vc20 /nn /unique

documento
  codice vc20 /nn /unique
  descrizione vc50 /nn
  data d /nn
  richiedente vc50 /nn
  stato_id /nn

documento_dettaglio
  documento_id /nn
  data d /nn
  utente vc50 /nn
  azione vc20 /nn
  stato_da_id /fk stato
  stato_a_id  /fk stato
# settings = { prefix: "D20", semantics: "CHAR", language: "EN", APEX: true }
*/
