-- drop table
drop table d08_azienda;

-- create tables
create table d08_azienda (
    id                             number generated by default on null as identity 
                                   constraint d08_azienda_id_pk primary key,
    nome                           varchar2(50 char) not null,
    piva                           varchar2(11 char),
    codfis                         varchar2(16 char),
    azienda_yn                     varchar2(1 char) default 'Y' constraint d08_azienda_azienda_yn_ck
                                   check (azienda_yn in ('Y','N')) not null,
    descrizione                    varchar2(4000 char),
    indirizzo                      varchar2(400 char),
    citta                          varchar2(400 char),
    cap                            varchar2(5 char),
	dipendenti					   number
)
;

-- load data
 
-- Generated by Quick SQL Mercoledì Aprile 12, 2023  09:47:25
 
/*
azienda
  nome vc50 /nn
  piva vc11
  codfis vc16
  azienda_yn /nn /check Y,N /default Y
  descrizione vc4000
  indirizzo vc400
  citta vc400
  cap vc5
  fatturato n
*/

# settings = { prefix: "D08", semantics: "CHAR", language: "EN", APEX: true }
*/