insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('GSC GROUP S.P.A.', 'GSC GROUP S.P.A.', 'VIA DELL''INDUSTRIA, 5', '36054', 'MONTEBELLO VICENTINO', null, '03559900240', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('MLE  S.R.L.', 'MLE  S.R.L.', 'VIA A . EINSTEIN, 35 INT.53', '50013', 'CAMPI BISENZIO', null, '06155390484', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('PROFILSIDER S.R.L.', 'PROFILSIDER S.R.L.', 'VIA DEI CANTIERI, 65/A', '90142', 'PALERMO', null, '04255040828', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SANGREGORIO VINCENZO', 'SANGREGORIO VINCENZO', 'Via di Cafaggio,88 Loc. S.Agata', '50038', 'SCARPERIA E SAN PIERO', 'SNGVCN55S23A462I', '05246790488', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('S.I.A.  S.R.L.', 'S.I.A.  S.R.L.', 'VIA BARLETTA, 96', '76123', 'ANDRIA', null, '06526460727', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('BALDI CLAUDIO PULIMENTATORE', 'BALDI CLAUDIO PULIMENTATORE', 'VIALE KENNEDY, 129 H', '50038', 'SCAPERIA', 'BLDCLD72D28D612U', '05105890486', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('GA.VO MECCANICA S.R.L.', 'GA.VO MECCANICA S.R.L.', 'Via Corsini, 950/A', '51036', 'Larciano', null, '01096360472', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('RENE'' CAOVILLA S.P.A.', 'RENE'' CAOVILLA S.P.A.', 'VIA PARADISI, 1', '30032', 'FIESSO D''ARTICO', null, '00166690271', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SYSTEMAG DI ANDREA RETTORE', 'SYSTEMAG DI ANDREA RETTORE', 'VIA CADUTI DI NASSIRYA, 13/1', '35011', 'RESCHIGLIANO DI CAMPODARSEGO', 'RTTNDR64S17G224T', '03969500283', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('MADEL S.P.A.', 'MADEL S.P.A.', 'VIA TORRICELLI 3', '48033', 'COTIGNOLA', null, '01155210394', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('FARMACIA D.SSA DI MATTEI & C. S.A.S.', 'FARMACIA D.SSA DI MATTEI & C. S.A.S.', 'CORSO ADRIATICO, 141', '64016', 'SANT''EGIDIO ALLA VIBRATA', null, '00946030673', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('FARMARREDA S.R.L.', 'FARMARREDA S.R.L.', 'Viale Italia, 147', '98124', 'Messina', null, '02859660835', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('METALLIKA ESPOSITORI S.R.L.', 'METALLIKA ESPOSITORI S.R.L.', 'Via lago di Tovel, 53', '36077', 'ALTAVILLA VICENTINA', null, '03359970245', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('DELLI GUANTI S.R.L.', 'DELLI GUANTI S.R.L.', 'PIAZZA GUIDO MONACO, 11', '52100', 'AREZZO', null, '01848750517', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('MESSINA S.A.S.', 'MESSINA S.A.S.', 'VIA CARLO ALBERTO', '20900', 'MONZA', null, '02828200960', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('LEM S.R.L. SOCIO UNICO', 'LEM S.R.L. SOCIO UNICO', 'Via L. Valiani, 55/59', '52025', 'Levane-Bucine', null, '00155740517', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('DEAGOSTINI INOX S.R.L.', 'DEAGOSTINI INOX S.R.L.', 'VIA MARCONI, 5/7', '28887', 'QUARNA SOTTO', null, '00536000037', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('THERMO MODUL DI BACICCHI MARIA GRAZIA', 'THERMO MODUL DI BACICCHI MARIA GRAZIA', 'Via L. Einaudi, 27', '41043', 'Casinalbo di Formigine', 'BCCMGR43S68G778T', '02112680364', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('GF SCALA S.R.L. UNIPERSONALE', 'GF SCALA S.R.L. UNIPERSONALE', 'Via Monte Santa Viola 12', '37142', 'Marzana', null, '02945890230', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('TIZIANA FIORENTINI  & C. S.A.S.', 'TIZIANA FIORENTINI  & C. S.A.S.', 'VIA FABRONI, 18', '50034', 'MARRADI', null, '04413680481', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SIDEM S.P.A.', 'SIDEM S.P.A.', 'Via Bergamo 94', '20882', 'Bellusco', '6664600159', '00833160963', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SALUS  S.A.S.', 'SALUS  S.A.S.', 'VIA GIOTTO, 24', '59016', 'POGGIO A CAIANO', null, '01992420974', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('CSKR DI GIUSEPPE FUOCO', 'CSKR DI GIUSEPPE FUOCO', 'VIA CARLO CARRA'', 49', '87036', 'SAPORITO DI RENDE', 'FCUGPP64A05D086L', '02782100784', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('DI CORI SERGIO S.R.L. UNIPERSONALE', 'DI CORI SERGIO S.R.L. UNIPERSONALE', 'Via Calcarelli snc', '00031', 'Artena', null, '09149201007', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('B & B BUSINESS S.R.L.', 'B & B BUSINESS S.R.L.', 'VIA SETTEVALLI, 133/C', '061xx', 'PERUGIA', null, '03114360542', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('BASF COATINGS SERVICES ITALY S.R.L.', 'BASF COATINGS SERVICES ITALY S.R.L.', 'ENTITY 1286 VIA MARCONATO, 8', '20811', 'CESANO MADERNO', null, '07028100969', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('HUMANITAS PRO CROCE VERDE S.R.L', 'HUMANITAS PRO CROCE VERDE S.R.L', 'Viale V.C. Castracani, n.468/D Via Romana II Trav.95', '55100', 'Lucca', null, '01762490462', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('FRIGOMATESE S.R.L.', 'FRIGOMATESE S.R.L.', 'VIA SANNITICA, 126/BIS', '81016', 'PIEDIMONTE MATESE', null, '02374330617', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('DE RIGO REFRIGERATION S.R.L.', 'DE RIGO REFRIGERATION S.R.L.', 'Via G. Buzzatti 10', '32036', 'Sedico', null, '00063550255', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ENOAGRICOLA ROSSI SRL UNIPERSONALE', 'ENOAGRICOLA ROSSI SRL UNIPERSONALE', 'VIA CORTONESE 36', '06019', 'CALZOLARO', null, '01206050542', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SUSSINO GAETANO', 'SUSSINO GAETANO', 'V.VOLONTARI DELLA LIBERTA'',72', '97019', 'VITTORIA', 'SSSGTN62P12M088L', '00407850882', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('BAGNI VETRERIE S.R.L.', 'BAGNI VETRERIE S.R.L.', 'via di Castelpulci 15/a', '50018', 'Scandicci', null, '00821790482', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('CAMAS S.R.L.', 'CAMAS S.R.L.', 'Viale delle Provincie, 6', '04012', 'Cisterna di LAtina', null, '01004200596', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('AISA S.A.S. DI SPACCA SILVIO & C.', 'AISA S.A.S. DI SPACCA SILVIO & C.', 'VIA TIBURTINA VALERIA, 412', '65129', 'PESCARA', null, '02018740684', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('CASEIF.AGR.DEL MILANELLO', 'CASEIF.AGR.DEL MILANELLO', 'Via Milanello, 1', '42040', 'Campegine', null, '00133180356', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ELETTRONICA CENTER S.R.L.', 'ELETTRONICA CENTER S.R.L.', 'Corso Numistrano, 26', '88046', 'Lamezia Terme', null, '03146290790', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SERMAC S.R.L.', 'SERMAC S.R.L.', 'VIA COMO, 3', '20834', 'NOVA MILANESE', null, '07817130961', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('TERRE DI LOPPIANO S.R.L.', 'TERRE DI LOPPIANO S.R.L.', 'LOC. BURCHIO SNC', '50064', 'INCISA VALDARNO', null, '05682780480', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('M.T.M. STAMPERIA', 'M.T.M. STAMPERIA', 'VIA DEI FOSSI, 35', '59100', 'PRATO', null, '00506260975', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('IL FOSSATO SRL DI GORI FRANCESCO & C.', 'IL FOSSATO SRL DI GORI FRANCESCO & C.', 'VIA DI BASCIANO, 805', '50036', 'VAGLIA', null, '05995510483', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('LATTERIA TULLIA SOC.COOP.AGR.', 'LATTERIA TULLIA SOC.COOP.AGR.', 'Via Tullie, 1', '42047', 'Rolo', null, '00143640357', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('AL ARREDAMENTI DI LUPPINO ANNUNZIATO', 'AL ARREDAMENTI DI LUPPINO ANNUNZIATO', 'VIA GAEZZA, 2', '89011', 'BAGNARA CALABRA', 'LPPNNZ61A02M018F', '00607710803', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('CASEIFICIO SAN DONATO SOC.AGR.COOP.', 'CASEIFICIO SAN DONATO SOC.AGR.COOP.', 'VIA PANICELLA, 21', '46014', 'Castellucchio', null, '00151450202', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SAVINOX S.R.L.', 'SAVINOX S.R.L.', 'Via Piave, 280', '17047', 'Vado Ligure', null, '00828070094', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SICILSCAFF S.R.L.', 'SICILSCAFF S.R.L.', 'C.DA PIRAINO S.S.192 KM.73.600', '95032', 'BELPASSO', null, '04950290876', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('TECNO SERVICE S.R.L.', 'TECNO SERVICE S.R.L.', 'V.MARTIRI DI CEFALONIA LOTTO 3', '54100', 'MASSA', null, '01148130451', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('FIERIS DI CASTELLI S.R.L.', 'FIERIS DI CASTELLI S.R.L.', 'Via Nazionale, 49', '28803', 'Verbania', null, '01428060030', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('G.F. DRINK S.R.L.', 'G.F. DRINK S.R.L.', 'VIA PADULLE, 381', '41055', 'MONTESE', null, '03498940364', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('DA UBALDO DI CERISETTI MAURO', 'DA UBALDO DI CERISETTI MAURO', 'VIA ROMA, 78', '57034', 'CAMPO NELL''ELBA', 'CRSMRA58P08H501N', '01316350493', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('IL TUO RISPARMIO S.R.L.', 'IL TUO RISPARMIO S.R.L.', 'VIA DEI MONTI TIBURTINI, 494', '00100', 'ROMA', null, '12182811005', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('VICECONTI S.N.C.', 'VICECONTI S.N.C.', 'Traversa Ammiraglio Ruggero, 20-22', '85044', 'LAURIA', null, '01601090762', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('VETEFAR S.R.L.', 'VETEFAR S.R.L.', 'Via Einstein, 41/43', '46030', 'S. Giorgio', '983430281', '10805330155', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('IMPRESS S.N.C.DI RUZZI & DESIDERIOSCIOLI', 'IMPRESS S.N.C.DI RUZZI & DESIDERIOSCIOLI', 'Via A. Gramsci 25', '66016', 'GUARDIAGRELE', null, '02438830693', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('CONIT CONSORZIO ITALIANO DI LAVORO', 'CONIT CONSORZIO ITALIANO DI LAVORO', 'STRADA STERPARA, 2', '04100', 'LATINA', null, '02631240591', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('NEAC COMPRESSOR SERVICE S.R.L.', 'NEAC COMPRESSOR SERVICE S.R.L.', 'Via Giorgio Steophenson, 94', '20157', 'MILANO', null, '04580540963', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ARREDITALIA S.R.L.', 'ARREDITALIA S.R.L.', 'VIA G. GENTILE, SN', '87067', 'ROSSANO', null, '02756230781', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SO.LOG. DI FRANCO SOLITO', 'SO.LOG. DI FRANCO SOLITO', 'Via Galateo, 3', '73044', 'Galatone', 'SLTFNC74L19D862O', '04283740753', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('MODENA TERMINAL  S.R.L.', 'MODENA TERMINAL  S.R.L.', 'Piazzale delle Nazioni, 14', '41011', 'Campogalliano', null, '00993810365', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('OVERLOG S.R.L.', 'OVERLOG S.R.L.', 'VIA A. MALIGNANI, 4/B', '33042', 'BUTTRIO', null, '02503470300', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('NC 2 GRID S.R.L.', 'NC 2 GRID S.R.L.', 'CORSO RE UMBERTO 1°, 63', '10128', 'TORINO', null, '06063220013', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('GAREMA S.R.L.', 'GAREMA S.R.L.', 'VIALE VITTORIO VENETO 31', '51100', 'PISTOIA', null, '01515960472', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ELFI S.P.A.', 'ELFI S.P.A.', 'Via Copernico 107', '47122', 'Forlì', null, '02698210404', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('D.B. GROUP S.P.A.', 'D.B. GROUP S.P.A.', 'VIA FELTRINA SUD 95', '31044', 'MONTEBELLUNA', '413430273', '03311000263', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('F.G.M.  S.R.L._', 'F.G.M.  S.R.L._', 'VIA FONTANA SAMBUCO, 21', '03100', 'FROSINONE', null, '02648300602', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('MIX S.R.L.', 'MIX S.R.L.', 'VIA L. BERETTI LANDI, 11', '29122', 'PIACENZA', null, '04859070965', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('GRUPPO ARCHETIPO S.R.L.', 'GRUPPO ARCHETIPO S.R.L.', 'VIA PALARCIANO, 104', '59013', 'MONTENURLO', null, '02301160970', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ETICHETTIFICIO 3P SNC DI LAMI PAOLO & C.', 'ETICHETTIFICIO 3P SNC DI LAMI PAOLO & C.', 'VIA STROGNANO, 21', '50059', 'VINCI', null, '03644410486', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('RVL SOLUTION S.R.L.', 'RVL SOLUTION S.R.L.', 'VIA ILARIA ALPI SNC', '50038', 'SCARPERIA E SAN PIERO', null, '06006130485', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('MZ ASPIRATORI S.P.A.', 'MZ ASPIRATORI S.P.A.', 'VIA CERTANI, 7', '40054', 'BUDRIO', '582450375', '00516881208', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SM PACK S.P.A.', 'SM PACK S.P.A.', 'Viale delle Industrie, 15', '20881', '20881', null, '01733760340', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('OMEGA IMPIANTI S.R.L.', 'OMEGA IMPIANTI S.R.L.', 'VIA MAMELI, 55/D', '18018', 'TAGGIA', null, '01503350082', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ALFAEDIL S.R.L.', 'ALFAEDIL S.R.L.', 'VIA MONTEMURLO, SNC', '59100', 'PRATO', null, '01720060977', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SEVI KABEL S.R.L.', 'SEVI KABEL S.R.L.', 'VIA DEI MARINAI D''ITALIA, 1', '10034', 'CHIVASSO', null, '05954050018', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ERREGI GRANDI CUCINE S.R.L.', 'ERREGI GRANDI CUCINE S.R.L.', 'VIA DON LUIGI STURZO, SNC', '89013', 'GIOIA TAURO', null, '02755060809', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ANDORNO S.N.C. DI ANDORNO A. & C.', 'ANDORNO S.N.C. DI ANDORNO A. & C.', 'Corso Allamano 202/A', '10098', 'Rivoli', '512960014', '00497900027', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('CONSORZIO SOLUZIONE MONTAGGI_', 'CONSORZIO SOLUZIONE MONTAGGI_', 'VIA PEDERZANA, 14/2', '40055', '40055', null, '03584711208', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('DOMO STUDIO', 'DOMO STUDIO', 'Via Garibaldi, 59', '10122', '10122', null, '08361420014', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('CMP SEMILAVORATI S.R.L.', 'CMP SEMILAVORATI S.R.L.', 'VIA RAFFAELLO, 34', '53036', 'POGGIBONSI', null, '01445760521', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('TRICOLORE S.R.L.', 'TRICOLORE S.R.L.', 'VOA F.LLI CORRADINI, 52', '42021', 'BIBBIANO', null, '02726670355', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('STERIS S.P.A.', 'STERIS S.P.A.', 'Via Volta 20', '24069', 'Trescore Balneario', '1729760163', '08949110152', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('PRAIM S.R.L.', 'PRAIM S.R.L.', 'Via Don Giovanni Minzoni', '23844', 'SIRONE', null, '01531740130', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('META SYSTEM S.P.A.', 'META SYSTEM S.P.A.', 'VIA GALIMBERTI 5', '42124', 'REGGIO EMILIA', null, '00271730350', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('C.M.R.M. DIVISION S.R.L.', 'C.M.R.M. DIVISION S.R.L.', 'VIA AMENDOLA, 5', '50058', 'SIGNA', null, '06807030488', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('MAREC S.R.L.', 'MAREC S.R.L.', 'Via dei Buonarroti Simoni n. 1', '50135', '50135', null, '06315380482', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('WINEEMOTION S.P.A.', 'WINEEMOTION S.P.A.', 'STRADA DI SNT''APPIANO 9A', '50021', 'BARBERINO VAL D''ELSA', null, '06231920486', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('IMPRESA PASQUALI GEOM. FERDINANDO S.A.S.', 'IMPRESA PASQUALI GEOM. FERDINANDO S.A.S.', 'VIA GARIBALDI 72/B', '40061', 'MINERBIO', null, '01542671209', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('FATTORIA I COLLAZZI SOCIETÀ AGRICOLA S.S .', 'FATTORIA I COLLAZZI SOCIETÀ AGRICOLA S.S .', 'VIA COLLERAMOLE 101', '50023', 'TAVARNUZZE', null, '00477420483', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ACCIAIOQUATTRO SRL UNIPERSONALE', 'ACCIAIOQUATTRO SRL UNIPERSONALE', 'VIA DEGLI OLMI 65/B', '50019', 'SESTO FIORENTINO', null, '05936730489', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SPINO & SPINA S.R.L.', 'SPINO & SPINA S.R.L.', 'VIA DELLA SELVA, 70', '50028', 'TAVARNELLE VAL DI PESA', null, '06807510489', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('CARROZZERIA RA.MA.CA S.N.C.DI MARCELLO CAPUTO & C.', 'CARROZZERIA RA.MA.CA S.N.C.DI MARCELLO CAPUTO & C.', 'STRADA FANTASIA, 30', '10040', 'LEINÌ', null, '05121710015', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('MASERATI S.P.A.', 'MASERATI S.P.A.', 'VIALE CIRO MENOTTI, 322', '41121', 'MODENA', null, '08245890010', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('NUOVA ARREDI NEGOZI S.R.L.S.', 'NUOVA ARREDI NEGOZI S.R.L.S.', 'C/Da Cuturella snc', '89843', 'Maierato - VIBO VALENZIA', null, '03272320791', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('FULL PRINT S.R.L.', 'FULL PRINT S.R.L.', 'Via Giulio Pastore, 1x', '48123', 'Ravenna', null, '01390090395', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('CREMATORIO DI FIRENZE S.P.A.', 'CREMATORIO DI FIRENZE S.P.A.', 'VIA BOLOGNESE 82R', '50139', 'FIRENZE', null, '06376920481', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ALDERIGHI IMPIANTI S.R.L._', 'ALDERIGHI IMPIANTI S.R.L._', 'VIA DEI CERAMISTI, 46', '50055', '50055', null, '05013040489', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('KRONN S.R.L.', 'KRONN S.R.L.', 'VIA BRIGATA TRIDENTINA, 6', '35020', 'PERNUMIA', null, '04773450285', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('STUDIO AUXILIUM', 'STUDIO AUXILIUM', 'Viale IV Novembre 49/b', '50032', 'Borgo San Lorenzo', null, '02180530483', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('GUIDI S.R.L.', 'GUIDI S.R.L.', 'Via delle Acacie, 2 - Zona Industriale D4', '28075', 'GRIGNASCO', null, '01872190036', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('LEONE S.R.L.', 'LEONE S.R.L.', 'VIA PASUBIO, 9', '37069', 'VILLAFRANCA', null, '03970700237', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('AUGUSTO BERNI S.P.A.', 'AUGUSTO BERNI S.P.A.', 'VIA LAMBERTINI,23', '40068', 'LOC.IDICE-S.LAZZARO DI SAVENA', '281080374', '00497121202', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('CASEIFICIO FERRETTI S.R.L.', 'CASEIFICIO FERRETTI S.R.L.', 'Via Verolanuova, 74', '25034', 'Orzinuovi', null, '03091710982', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('AZ.AGRICOLA FERRARETTO SIMONETTA', 'AZ.AGRICOLA FERRARETTO SIMONETTA', 'VIA ROMA,82', '35040', 'CARCERI', null, '04087290286', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('BIONDI MICHELA', 'BIONDI MICHELA', 'VIA VICINALE BOSCA 1', '48020', 'RUSSI', null, '0280590396', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ITALGRANITI GROUP S.P.A.', 'ITALGRANITI GROUP S.P.A.', 'Via Radici in Piano, 355', '41043', 'Casinalbo di Formigine', null, '03294200369', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('OCIS F.LLI BETTUCCHI SNC', 'OCIS F.LLI BETTUCCHI SNC', 'Via Passo del Soldato 3', '40030', 'Castel di Casio', '395110372', '00507581205', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('GERARD LOFT S.R.L.', 'GERARD LOFT S.R.L.', 'VIA DEI PECORI 34/36/38/40R', '50123', 'FIRENZE', null, '06470550481', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('F.M.  S.R.L.', 'F.M.  S.R.L.', 'VIA DEI CARROZZIERI, 9', '55041', 'CAPEZZANO PIANORE', null, '01891430462', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('D. & D. ITALIA S.P.A.', 'D. & D. ITALIA S.P.A.', 'VIA IRNO', '84098', 'PIOTECAGNANO/FAIANO', null, '02927630653', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('MELUCCI S.R.L.', 'MELUCCI S.R.L.', 'VICO MILANO, 18', '80142', 'NAPOLI', null, '06008391218', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('C.M.SERVICES S.R.L.', 'C.M.SERVICES S.R.L.', 'VIA A.VOLTA 18', '95122', 'CATANIA', null, '04193330877', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ARGO TRACTORS S.P.A._', 'ARGO TRACTORS S.P.A._', 'VIA MATTEOTTI 7', '42042', '42042', '3876290374', '02291970354', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('RAGGI MARCO', 'RAGGI MARCO', 'VIA GIORGIO VASARI', '50038', 'SCARPERIA E SAN PIERO', 'RGGMRC62R25G999S', '06814530488', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('DIGITAL IMPIANTI S.R.L.', 'DIGITAL IMPIANTI S.R.L.', 'VIA FLAVIA 130', '34147', 'TRIESTE', null, '01036000329', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('GSV SPECIAL  WELDING S.R.L.', 'GSV SPECIAL  WELDING S.R.L.', 'LOC. PETRONA, SNC', '50038', 'SCARPERIA E SAN PIERO', null, '06716360489', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ERRE DI RICCARDO MARINELLI SAS', 'ERRE DI RICCARDO MARINELLI SAS', 'VIA CANCIELLIERA 16', '00040', 'ARICCIA', null, '05205391005', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('COMEEL S.R.L.A SOCIO UNICO', 'COMEEL S.R.L.A SOCIO UNICO', 'VIA A.EINSTEIN 35/49', '50013', 'CAMPI BISENZIO', '2294930488', '01872140973', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('LIBRERIA IL MAGNIFICO DI LORENZO CHIARI', 'LIBRERIA IL MAGNIFICO DI LORENZO CHIARI', 'Via Alfani, 95R', '50121', 'FIRENZE', 'CHRLNZ91L23D612F', '06703340486', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('FABRITEX S.R.L.', 'FABRITEX S.R.L.', 'VIA UDINE 83/85', '59013', 'MONTEMURLO', '1380860484', '00420570475', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('COOP.CASEARIA AGRINASCENTE SOC.AGR.COOP.', 'COOP.CASEARIA AGRINASCENTE SOC.AGR.COOP.', 'Via S. Michele Campagna, 22/b', '43036', 'Fidenza', null, '00574930343', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('LABORATORIO TERAPEUTICO M.R. S.R.L.', 'LABORATORIO TERAPEUTICO M.R. S.R.L.', 'VIA DOMENICO VENEZIANO 13', '50143', 'FIRENZE', null, '00482630480', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('PRATO MULETTI DI CALISTRI CLAUDIO', 'PRATO MULETTI DI CALISTRI CLAUDIO', 'VIA RAVENNA 17', '59013', 'MONTEMURLO', 'CLSCLD58R28G999O', '02307030979', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('INGROVISION S.R.L.', 'INGROVISION S.R.L.', 'VIA A.DE GASPERI 83/D', '55100', 'LUCCA', null, '02174800462', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('PROGETTO ENERGIA S.R.L. SOCIO UNICO', 'PROGETTO ENERGIA S.R.L. SOCIO UNICO', 'Via Aristotele, 32', '42122', 'REGGIO EMILIA', null, '02244360356', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('LOGICUS S.R.L. SOC.UNIPERSONALE', 'LOGICUS S.R.L. SOC.UNIPERSONALE', 'Via Strà 59', '37030', 'Colognola ai Colli', null, '04471320236', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('MENCI NORD S.R.L.', 'MENCI NORD S.R.L.', 'V.DELL''INDUSTRIA E ARTIGIANATO', '35010', 'CARMIGNANO DI BRENTA', null, '04158850281', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ASSOCIAZIONE JUPPITER ONLUS', 'ASSOCIAZIONE JUPPITER ONLUS', 'Piazza 7 Luglio, 6', '01012', 'CAPRANICA', null, '01409210562', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SPORT CAR S.N.C.', 'SPORT CAR S.N.C.', 'VIA DELLA LIBERAZIONE, 61', '61030', 'CARTOCETO', null, '02227290414', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('CASAMODA 28 S.R.L.', 'CASAMODA 28 S.R.L.', 'VIA BANDINI, 23/25', '41053', 'MARANELLO', null, '03194170365', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('FGM GIAMBELLINI S.R.L.', 'FGM GIAMBELLINI S.R.L.', 'VIA TOSCANINI, 50/52', '20038', 'SEREGNO', '1492320153', '00714990967', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('MANTELLI GINA E BRUNA & C. S.N.C.', 'MANTELLI GINA E BRUNA & C. S.N.C.', 'PIAZZA CAVOUR, 80', '50031', 'BARBERINO DI MUGELLO', null, '01942820489', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('VICINI S.P.A.', 'VICINI S.P.A.', 'VIA DELLA CUPOLA, 239', '50145', 'FIRENZE', null, '01420320481', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ITALGIAD S.R.L.', 'ITALGIAD S.R.L.', 'VIA DEL COMMERCIO, 10', null, 'PIERANTONIO', null, '02852050547', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('TENUTA AGRICOLA RUPOLI S.A.S.', 'TENUTA AGRICOLA RUPOLI S.A.S.', 'LOCALITA'' RUPOLI', '50020', 'PANZANO IN CHIANTI', null, '05325910486', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ARIES S.N.C. DI ADDA GIANPAOLO & C.', 'ARIES S.N.C. DI ADDA GIANPAOLO & C.', 'VIA VENEZIA, 105', '31020', 'TEZZE DI PIAVE', null, '00880370267', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SAT DISTRIBUZIONE DI SKOPETZ ALFRED TIBERIU', 'SAT DISTRIBUZIONE DI SKOPETZ ALFRED TIBERIU', 'VIA MARAGLIANO, 7 R', '50144', 'FIRENZE', 'SKPLRD77M08Z129A', '04631700657', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('DESIGN INNOVATION S.R.L.', 'DESIGN INNOVATION S.R.L.', 'VIA THAON DI REVEL, 21', '20159', 'MILANO', null, '12254140150', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('PIESSEFOTO S.R.L.', 'PIESSEFOTO S.R.L.', 'VIA DELL''ARTIGIANATO, 10/10', '40023', 'CASTEL GUELFO', null, '02152731200', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('EMI DI STEFANINI SIMONE', 'EMI DI STEFANINI SIMONE', 'VIA B. CORSINI, 6', '50037', 'SAN PIERO A SIEVE', 'STFSMN70T06D612H', '04122920483', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('FARMACIA LABROZZI DOTT.SSA M.ANTONIETTA', 'FARMACIA LABROZZI DOTT.SSA M.ANTONIETTA', 'VIALE PIETRAVALLE, 17', '86038', 'PETACCIO', 'LBRMNT61B53A485S', '00792030702', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('BIOPLAST S.R.L.', 'BIOPLAST S.R.L.', 'VIA DURANO, 26', '84014', 'NOCERA INFERIORE', null, '02576760652', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('DISTILLERIE MAZZARI S.P.A._', 'DISTILLERIE MAZZARI S.P.A._', 'VIA GIARDINO, 6', '48020', '48020', null, '00454950395', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('AGRI 90 S.T.L.', 'AGRI 90 S.T.L.', 'VIA ALESSANDRO DELLA SETA, 11', null, 'R O M A', '8406310584', '02046691008', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('CRUCIANI GROUP S.R.L.', 'CRUCIANI GROUP S.R.L.', 'VIA ROMA, 149', '00040', 'POMEZIA', null, '08397251003', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('AIR COLD REFRIGERATION S.N.C.', 'AIR COLD REFRIGERATION S.N.C.', 'VIA CASTEL DEL MONTE, 131/B', '70033', 'CORATO', null, '06008360726', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('EXPOTRANS S.R.L.', 'EXPOTRANS S.R.L.', 'VIA PORTUENSE, 1555', '00100', 'ROMA', null, '03903121006', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('S.V.A. SERVIZIO AUDIO VIDEO S.N.C.', 'S.V.A. SERVIZIO AUDIO VIDEO S.N.C.', 'VIA MONTANARA, 22/27', '55100', 'LUCCA', null, '01314910462', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SIDERURGICA DEL POLESINE S.R.L.', 'SIDERURGICA DEL POLESINE S.R.L.', 'Viale delle Industrie 9', '45100', 'Rovigo', null, '00324610294', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('AUTOSERVICE VALENTINI S.A.S.', 'AUTOSERVICE VALENTINI S.A.S.', 'VIA DEL PIANO, 11/B', null, 'PONTE NUOVO/TORGIANO', null, '01534490543', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('IL MARCHIO D''ORO S.R.L.', 'IL MARCHIO D''ORO S.R.L.', 'VIA DI PORTO, 22/A', '50018', 'BADIA A SETTIMO', null, '05276800488', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SIME IDROMECCANICA S.R.L.', 'SIME IDROMECCANICA S.R.L.', 'Via delle Ville 5/a', '42016', 'Guastalla', null, '02305090355', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('RIGACCI & PETRIOLI S.R.L.', 'RIGACCI & PETRIOLI S.R.L.', 'VIA F. BONAINI, 5/7', '50134', 'FIRENZE', null, '05879280484', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('A.P.I.  S.R.L.', 'A.P.I.  S.R.L.', 'VIA TASSO, 12', '81020', 'SAN NICOLA LA STRADA', null, '03442530618', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SOLON S.P.A.   SOCIO UNICO', 'SOLON S.P.A.   SOCIO UNICO', 'VIA INDUSTRIA E ARTIGIANATO,22', '35010', 'CARMIGNANO DI BRENTA', null, '04039610284', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SANTICCIOLI OFF ROAD S.R.L.', 'SANTICCIOLI OFF ROAD S.R.L.', 'RIGUTINO OVEST, 234/H', '52100', 'AREZZO', null, '01821080510', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('MUGELLO CIRCUIT S.P.A.', 'MUGELLO CIRCUIT S.P.A.', 'VIA SENNI N.15', '50038', 'SCARPERIA E SAN PIERO', null, '09397670010', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('MG S.P.A. LAVORAZ.MAT.PLASTICHE', 'MG S.P.A. LAVORAZ.MAT.PLASTICHE', 'VIA G. STEFANI, 48', '36050', 'LANZE'' DI QUINTO VICENTINO', null, '00171890247', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SYREN S.R.L.', 'SYREN S.R.L.', 'VIA FIUME SAMARA, SNC', '65016', 'MONTESILVANO', null, '01846280681', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('HOLGER CHRISTIANSEN ITALIA S.R.L.', 'HOLGER CHRISTIANSEN ITALIA S.R.L.', 'VIA CICOGNA, 27/29', '40068', 'SAN LAZZARO DI SAVENA', '13225940157', '02144311202', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ENOUMBRIA S.R.L.', 'ENOUMBRIA S.R.L.', 'VIA PALERMO, 1/A', '06034', 'FOLIGNO', null, '02318930548', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('MENETTI LAURA', 'MENETTI LAURA', 'VIALE DEI MILLE, 20', '50100', 'FIRENZE', 'MNTLRA60D64E289J', '04189060488', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('BARDAZZI DOTT.GIOVANNI', 'BARDAZZI DOTT.GIOVANNI', 'VIA S. SIGHELE, 54', '50134', 'FIRENZE', 'BRDGNN38M06M059U', '04629710486', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ETRURIA STAR DI BARTOLOMEI G.PAOLO', 'ETRURIA STAR DI BARTOLOMEI G.PAOLO', 'VIA SARZANESE VALDERA, 786/788', '55062', 'CASTELVECCHIO DI COMPITO', 'BRTGPL40S30B648L', '00010060465', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('CE.DI.AL. S.R.L.', 'CE.DI.AL. S.R.L.', 'VIA LA MARMORA, 14', '92024', 'CANICATTI', null, '02067930848', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('FAGIMA FRESATRICI S.R.L.', 'FAGIMA FRESATRICI S.R.L.', 'VIA L.GHIBERTI LOC.PONTENUOVO', '50028', 'TAVARNELLE VAL DI PESA', null, '03789270489', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('DEL MORINO S.R.L._', 'DEL MORINO S.R.L._', 'VIA CARONI DI SOTTO, 19', '52033', '52033', null, '01041010511', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SHOCK ! SOLUTION S.R.L.', 'SHOCK ! SOLUTION S.R.L.', 'VIA PESCIATINA, 166/B', '55012', 'LUNATA', null, '01740890460', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('LADY V S.R.L.', 'LADY V S.R.L.', 'VIA DELL''AGRICOLTURA, 37/39', '59013', 'MONTEMURLO', null, '01553930973', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ROLLA DI RANIERO LOMBARDI & C. S.A.', 'ROLLA DI RANIERO LOMBARDI & C. S.A.', 'VIA DEI PESCATORI, 38', '55049', 'VIAREGGIO', null, '02036950463', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ALMA S.P.A.', 'ALMA S.P.A.', 'VIA DONATELLO, 4', '50013', 'CAPALLE', null, '01879860979', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('HTC  S.P.A.', 'HTC  S.P.A.', 'VIA G.GIULIANI Z.I.LA PACIANA', '06034', 'FOLIGNO', null, '02846730543', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('STEMAU S.R.L.', 'STEMAU S.R.L.', 'VIA CICOGNA, 33', '40068', 'SAN LAZZARO DI SAVENA', null, '03527450377', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('PROGETTO MOBILI S.R.L.', 'PROGETTO MOBILI S.R.L.', 'VIALE J.F. KENNEDY, 85', '81031', 'AVERSA', null, '02501490615', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('GENERAL OFFICE S.R.L.', 'GENERAL OFFICE S.R.L.', 'CORSO MEDITERRANEO, 425', '87029', 'SCALEA', null, '02441510787', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('TREZZA REFRIGERAZIONE DI ANTONIO TREZZA', 'TREZZA REFRIGERAZIONE DI ANTONIO TREZZA', 'VIA CANGIANI, 15', '84018', 'SCAFATI', 'TRZNTN65H10I483J', '03636940656', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('VITAMIN CENTER S.R.L.', 'VITAMIN CENTER S.R.L.', 'VIA MARINO SERENARI, 6/A', '40013', 'CASTEL MAGGIORE', null, '02255511202', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ELETTROTECH S.N.C. DI STRIGHINI M. & BRESCIANI F.', 'ELETTROTECH S.N.C. DI STRIGHINI M. & BRESCIANI F.', 'VIA VENETO, 2/4', '46040', 'PIUBEGA', null, '02099930204', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('JANNICOLA METALMECCANICA S.R.L.', 'JANNICOLA METALMECCANICA S.R.L.', 'VIA TOR TRE PONTI, 70', '04100', 'LATINA', null, '00961200599', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('TPC GROUP S.R.L.', 'TPC GROUP S.R.L.', null, '52014', 'PRATO', null, '01899370512', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('MORETTI SILVANO S.N.C. DI MORETTI', 'MORETTI SILVANO S.N.C. DI MORETTI', 'VIA GIORDANIA, 10/12', '58100', 'GROSSETO', null, '01089970535', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('CARTOLERIA RUSSO & RUSSO S.R.L.', 'CARTOLERIA RUSSO & RUSSO S.R.L.', 'VIA OVIDIO 54/58', '92019', 'SCIACCA', null, '02450790841', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('FLOEMY S.R.L.', 'FLOEMY S.R.L.', 'S.S.18 LOC. PAPALEONE', '84025', 'EBOLI', null, '03727450656', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('HOBBITALIA 2 S.R.L.', 'HOBBITALIA 2 S.R.L.', 'VIA DEGLI ARTISTI, 11/D', '50121', 'FIRENZE', null, '03368940486', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('AUTOTRASPORTI LAZZARATO S.R.L.', 'AUTOTRASPORTI LAZZARATO S.R.L.', 'VIA TOGLIATTI, 26', '20030', 'SENAGO', null, '05526160964', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('LUXURIA DI NERI GIANNA', 'LUXURIA DI NERI GIANNA', 'P.LE CURTATONE E MONTANARA, 48', '50032', 'BORGO SAN LORENZO', 'NREGNN57S56D612F', '05796440484', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ASTOR ARREDAMENTI SNC DI PEDERZINI MASSIMILIANO', 'ASTOR ARREDAMENTI SNC DI PEDERZINI MASSIMILIANO', 'VIA A.VOLTA, 30', '24011', 'ALME''', null, '03316720162', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('EMPORIO AGRARIO DI PASSINI FABIO', 'EMPORIO AGRARIO DI PASSINI FABIO', 'VIA LITORANEA, 227', '04100', 'BORGO GRAPPA', 'PSSFBA78P09E472I', '01938400593', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SPAZIANI ARREDA S.R.L.', 'SPAZIANI ARREDA S.R.L.', 'VIA IDROVORA, 11', '04100', 'LATINA', null, '02291610596', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('LIBRERIA PIROLA MAGGIOLI DI TEDESCO F.', 'LIBRERIA PIROLA MAGGIOLI DI TEDESCO F.', 'CORSO VITTORIO VENETO, 300', '92026', 'FAVARA', 'TDSFNC64R69A089K', '01726550849', 'N');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('SPORTING CLUB BORGO NUOVO', 'SPORTING CLUB BORGO NUOVO', 'VIA ILARIA ALPI SNC.', '50037', 'SAN PIERO A SIEVE', null, '05718920480', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ALESSIA S.N.C.', 'ALESSIA S.N.C.', 'VIA DI BROZZI, 64', '50145', 'FIRENZE', null, '02194630485', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ARROW SPECIAL PARTS S.P.A.', 'ARROW SPECIAL PARTS S.P.A.', 'VIA CITERNENSE, 128/130', '06016', 'SAN GIUSTINO', null, '01512120542', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('IMMOBILIARE ARTICOLO QUARANTACINQUE S.R.L.', 'IMMOBILIARE ARTICOLO QUARANTACINQUE S.R.L.', 'VIA VASCO DE GAMA, 25', '50127', 'FIRENZE', null, '05411160483', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('ASIT S.P.A.', 'ASIT S.P.A.', 'VIA GORETTA, 90/F', '10072', 'CASELLE TORINESE', null, '06221270017', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('CENTRO BEVANDE SNC', 'CENTRO BEVANDE SNC', 'Via Roma, 394', '50028', 'Tavernelle Val di Pesa', null, '03665080481', 'Y');

insert into D08_AZIENDA (NOME, DESCRIZIONE, INDIRIZZO, CAP, CITTA, CODFIS, PIVA, AZIENDA_YN)
values ('GAMMA PACK S.P.A.', 'GAMMA PACK S.P.A.', 'VIA DON CORCHIA', '43013', 'LANGHIRANO', null, '00422910349', 'Y');
