select ID_1,
       ID,
       GEO_POINT_2D,
       GEO_SHAPE,
       NAME,
       ETICHETTA,
       NOTETESTO,
       NUMEROANTICO,
       NUMEROMODERNO,
       LINK1,
       LINK2,
       LINK3,
       PIANI,
       ARCATE,
       ARCHITRAVATE,
       ARCHITRAVATE_CON_COLONNE_DI_LEGNO,
       ARCHIVOLTI,
       MODIGLIONI,
       MENSOLONI_ARCHITRAVATI,
       STALLA_E,
       FIENILE_I,
       RIMESSA_E,
       SCUDERIA_E,
       ATTIVITA_COMMERCIALI_PRODUTTIVE_1,
       ATTIVITA_COMMERCIALI_PRODUTTIVE_2,
       ATTIVITA_COMMERCIALI_PRODUTTIVE_3,
       ATTIVITA_COMMERCIALI_PRODUTTIVE_4,
       ATTIVITA_COMMERCIALI_PRODUTTIVE_5,
	   decode(link1, '-', decode(link2, '-', decode(link3,'-', 'httpwww.originebologna.com', link3), link2), link1) url,
	   decode(PIANI, '-', 1, 3to_number(piani)) n_piani
  from D10_ORIGINI
