-- drop objects
drop table d07_tipo_documento cascade constraints;
drop table d07_documento cascade constraints;
drop package d07_tipo_documento_api;
drop package d07_documento_api;

-- create tables
create table d07_tipo_documento (
    id                             number generated by default on null as identity 
                                   constraint d07_tipo_documento_id_pk primary key,
    tipo_documento                 varchar2(8 char)
                                   constraint d07_tipo_docu_tipo_documen_unq unique not null
)
;

create table d07_documento (
    id                             number generated by default on null as identity 
                                   constraint d07_documento_id_pk primary key,
    tipo_documento_id              number
                                   constraint d07_documento_tipo_document_fk
                                   references d07_tipo_documento on delete cascade,
    codice                         varchar2(20 char)
                                   constraint d07_documento_codice_unq unique not null,
    data_documento                 date not null,
    firma_yn                       varchar2(1 char) default 'N' constraint d07_documento_firma_yn_ck
                                   check (firma_yn in ('Y','N')) not null,
    categoria                      varchar2(100 char)
)
;

-- table index
create index d07_documento_i1 on d07_documento (tipo_documento_id);


-- APIs --
create or replace package d07_tipo_documento_api
is
 
    /* example:
        declare
            l_tipo_documento                varchar2(8);
        begin
        d07_tipo_documento_api.get_row (
            p_id                            => 1,
            p_tipo_documento                => l_tipo_documento
            );
        end;
    */

    procedure get_row (
        p_id                           in  number,
        p_tipo_documento               out varchar2
    );
 
    /* example:
        begin
        d07_tipo_documento_api.insert_row (
            p_id                          => null,
            p_tipo_documento              => null
            );
        end;
    */

    procedure insert_row  (
        p_id                           in number default null,
        p_tipo_documento               in varchar2 default null
    );
    procedure update_row  (
        p_id                           in number default null,
        p_tipo_documento               in varchar2 default null
    );
    procedure delete_row (
        p_id                           in number
    );
end d07_tipo_documento_api;
/


create or replace package  body d07_tipo_documento_api
is
 
    procedure get_row (
        p_id                           in  number,
        p_tipo_documento               out varchar2
    )
    is
    begin
        for c1 in (select * from d07_tipo_documento where id = p_id) loop
            p_tipo_documento := c1.tipo_documento;
        end loop;
    end get_row;

 
    procedure insert_row  (
        p_id                           in number default null,
        p_tipo_documento               in varchar2 default null
    )
    is
    begin
        insert into d07_tipo_documento (
            id,
            tipo_documento
        ) values (
            p_id,
            p_tipo_documento
        );
    end insert_row;

    procedure update_row  (
        p_id                           in number default null,
        p_tipo_documento               in varchar2 default null
    )
    is
    begin
        update  d07_tipo_documento set 
            id = p_id,
            tipo_documento = p_tipo_documento
        where id = p_id;
    end update_row;

    procedure delete_row (
        p_id                           in number
    )
    is
    begin
        delete from d07_tipo_documento where id = p_id;
    end delete_row;

end d07_tipo_documento_api;
/


create or replace package d07_documento_api
is
 
    /* example:
        declare
            l_tipo_documento_id             number;
            l_codice                        varchar2(20);
            l_data_documento                date;
            l_firma_yn                      varchar2(1);
            l_categoria                     varchar2(100);
        begin
        d07_documento_api.get_row (
            p_id                            => 1,
            p_tipo_documento_id             => l_tipo_documento_id,
            p_codice                        => l_codice,
            p_data_documento                => l_data_documento,
            p_firma_yn                      => l_firma_yn,
            p_categoria                     => l_categoria
            );
        end;
    */

    procedure get_row (
        p_id                           in  number,
        p_tipo_documento_id            out number,
        p_codice                       out varchar2,
        p_data_documento               out date,
        p_firma_yn                     out varchar2,
        p_categoria                    out varchar2
    );
 
    /* example:
        begin
        d07_documento_api.insert_row (
            p_id                          => null,
            p_tipo_documento_id           => null,
            p_codice                      => null,
            p_data_documento              => null,
            p_firma_yn                    => null,
            p_categoria                   => null
            );
        end;
    */

    procedure insert_row  (
        p_id                           in number default null,
        p_tipo_documento_id            in number default null,
        p_codice                       in varchar2 default null,
        p_data_documento               in date default null,
        p_firma_yn                     in varchar2 default null,
        p_categoria                    in varchar2 default null
    );
    procedure update_row  (
        p_id                           in number default null,
        p_tipo_documento_id            in number default null,
        p_codice                       in varchar2 default null,
        p_data_documento               in date default null,
        p_firma_yn                     in varchar2 default null,
        p_categoria                    in varchar2 default null
    );
    procedure delete_row (
        p_id                           in number
    );
end d07_documento_api;
/


create or replace package  body d07_documento_api
is
 
    procedure get_row (
        p_id                           in  number,
        p_tipo_documento_id            out number,
        p_codice                       out varchar2,
        p_data_documento               out date,
        p_firma_yn                     out varchar2,
        p_categoria                    out varchar2
    )
    is
    begin
        for c1 in (select * from d07_documento where id = p_id) loop
            p_tipo_documento_id := c1.tipo_documento_id;
            p_codice := c1.codice;
            p_data_documento := c1.data_documento;
            p_firma_yn := c1.firma_yn;
            p_categoria := c1.categoria;
        end loop;
    end get_row;

 
    procedure insert_row  (
        p_id                           in number default null,
        p_tipo_documento_id            in number default null,
        p_codice                       in varchar2 default null,
        p_data_documento               in date default null,
        p_firma_yn                     in varchar2 default null,
        p_categoria                    in varchar2 default null
    )
    is
    begin
        insert into d07_documento (
            id,
            tipo_documento_id,
            codice,
            data_documento,
            firma_yn,
            categoria
        ) values (
            p_id,
            p_tipo_documento_id,
            p_codice,
            p_data_documento,
            p_firma_yn,
            p_categoria
        );
    end insert_row;

    procedure update_row  (
        p_id                           in number default null,
        p_tipo_documento_id            in number default null,
        p_codice                       in varchar2 default null,
        p_data_documento               in date default null,
        p_firma_yn                     in varchar2 default null,
        p_categoria                    in varchar2 default null
    )
    is
    begin
        update  d07_documento set 
            id = p_id,
            tipo_documento_id = p_tipo_documento_id,
            codice = p_codice,
            data_documento = p_data_documento,
            firma_yn = p_firma_yn,
            categoria = p_categoria
        where id = p_id;
    end update_row;

    procedure delete_row (
        p_id                           in number
    )
    is
    begin
        delete from d07_documento where id = p_id;
    end delete_row;

end d07_documento_api;
/



-- load data
 
insert into d07_tipo_documento (
    id,
    tipo_documento
) values (
    1,
    'TIPO UNO'
);

insert into d07_tipo_documento (
    id,
    tipo_documento
) values (
    2,
    'TIPO DUE'
);

insert into d07_tipo_documento (
    id,
    tipo_documento
) values (
    3,
    'TIPO TRE'
);

commit;

alter table d07_tipo_documento
modify id generated always as identity restart start with 4;
 
-- load data
 
-- Generated by Quick SQL Tuesday March 07, 2023  07:55:46
 
/*
tipo documento /insert 3
  tipo documento /nn /values tipo uno, tipo due, tipo tre /unique
  documento
    codice vc20 /nn /unique
    data documento d /nn
    firma_yn /nn /default N
    categoria vc100

# settings = { prefix: "d07", semantics: "CHAR", API: true, drop: true, language: "EN", APEX: true }
*/
