-- istruzioni valide nel nuovo 23c: if exists if not exists

--drop trigger if exists d07_tabella_biu;
--drop table if exists d07_tabella;

-- create tables
create table if not exists d07_tabella (
    id                             number generated by default on null as identity 
                                   constraint d07_tabella_id_pk primary key,
    campo                          varchar2(4000 char),
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;


-- triggers
create or replace trigger d07_tabella_biu
    before insert or update 
    on d07_tabella
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d07_tabella_biu;
/

-- load data
 
-- Generated by Quick SQL Tuesday April 11, 2023  04:47:44
 
/*
tabella
  campo
#auditcols:true

# settings = { prefix: "D07", semantics: "CHAR", auditCols: true, language: "EN", APEX: true }
*/
