-- create tables
create table d05_persona (
    id                             number generated by default on null as identity 
                                   constraint d05_persona_id_pk primary key,
    nome                           varchar2(20 char) not null,
    foto                           blob,
    foto_filename                  varchar2(512 char),
    foto_mimetype                  varchar2(512 char),
    foto_charset                   varchar2(512 char),
    foto_lastupd                   date
)
;

-- load data
 
-- Generated by Quick SQL Tuesday April 04, 2023  04:16:01
 
/*
persona
  nome vc20 /nn
  foto file


# settings = { prefix: "D05", semantics: "CHAR", language: "EN", APEX: true }
*/
