create table d05_azienda (
    id                             number generated by default on null as identity 
                                   constraint d05_azienda_id_pk primary key,
    ragione_sociale                varchar2(100 char) not null,
    tipo_azienda                   varchar2(1 char),
    indirizzo                      varchar2(4000 char),
    cap                            varchar2(5 char),
    citta                          varchar2(4000 char),
    comune                         varchar2(6 char),
    provincia                      varchar2(2 char),
    regione                        varchar2(2 char),
    nazione                        varchar2(3 char) default 'ITA',
    telefono                       varchar2(50 char),
    email                          varchar2(50 char),
    codice_iva                     varchar2(11 char),
    codice_fiscale                 varchar2(16 char),
    tipo_persona                   varchar2(1 char),
    codice_sdi                     varchar2(5 char),
    tipo_pagamento                 varchar2(1 char),
    banca                          varchar2(100 char),
    iban                           varchar2(27 char),
    aggiornamento                  date,
    attiva                         varchar2(1 char),
    logo                            blob,
    motto                           clob,
    coordinate_json                varchar2(4000 char)
)
;
